let symbols = {
    consonants: [],
    vowels: {
        'close_back_rounded_vowel': 'u',
        'close_back_unrounded_vowel': 'ɯ',
        'close_central_rounded_vowel': 'ʉ',
        'close_central_unrounded_vowel': 'ɨ',
        'close_front_rounded_vowel': 'y',
        'close_front_unrounded_vowel': 'i',
        'close-mid_back_rounded_vowel': 'o',
        'close-mid_back_unrounded_vowel': 'ɤ',
        'close-mid_central_rounded_vowel': 'ɵ',
        'close-mid_central_unrounded_vowel': 'ɘ',
        'close-mid_front_rounded_vowel': 'ø',
        'close-mid_front_unrounded_vowel': 'e',
        'mid-central_vowel': 'ə',
        'near-close_near-back_rounded_vowel': 'ʊ',
        'near-close_near-front_rounded_vowel': 'ʏ',
        'near-close_near-front_unrounded_vowel': 'ɪ',
        'near-open_central_unrounded_vowel': 'ɐ',
        'near-open_front_unrounded_vowel': 'æ',
        'open_back_rounded_vowel': 'ɒ',
        'open_back_unrounded_vowel': 'ɑ',
        'open_central_unrounded_vowel': 'ä',
        'open_front_rounded_vowel': 'ɶ',
        'open_front_unrounded_vowel': 'a',
        'open-mid_back_rounded_vowel': 'ɔ',
        'open-mid_back_unrounded_vowel': 'ʌ',
        'open-mid_central_rounded_vowel': 'ɞ',
        'open-mid_central_unrounded_vowel': 'ɜ',
        'open-mid_front_rounded_vowel': 'œ',
        'open-mid_front_unrounded_vowel': 'ɛ'
    }
};

let specs = {
    "default": {
        consonants: {
            "V_alveolar_approximant": true,
            "V_alveolar_fricative": true,
            "V_alveolar_lateral_approximant": true,
            "V_alveolar_lateral_fricative": true,
            "V_alveolar_nasal": true,
            "V_alveolar_plosive": true,
            "V_alveolar_tap": true,
            "V_alveolar_trill": true,
            "V_bilabial_fricative": true,
            "V_bilabial_nasal": true,
            "V_bilabial_plosive": true,
            "V_bilabial_trill": true,
            "V_dental_fricative": true,
            "V_glottal_fricative": true,
            "V_labiodental_approximant": true,
            "V_labiodental_flap": true,
            "V_labiodental_fricative": true,
            "V_labiodental_nasal": true,
            "V_palatal_approximant": true,
            "V_palatal_fricative": true,
            "V_palatal_lateral_approximant": true,
            "V_palatal_nasal": true,
            "V_palatal_plosive": true,
            "V_pharyngeal_fricative": true,
            "V_postalveolar_fricative": true,
            "V_retroflex_approximant": true,
            "V_retroflex_flap": true,
            "V_retroflex_fricative": true,
            "V_retroflex_lateral approximant": true,
            "V_retroflex_nasal": true,
            "V_retroflex_plosive": true,
            "V_uvular_fricative": true,
            "V_uvular_nasal": true,
            "V_uvular_plosive": true,
            "V_uvular_trill": true,
            "V_velar_approximant": true,
            "V_velar_fricative": true,
            "V_velar_lateral_approximant": true,
            "V_velar_nasal": true,
            "V_velar_plosive": true,
            "VL_alveolar_fricative": true,
            "VL_alveolar_lateral_fricative": true,
            "VL_alveolar_plosive": true,
            "VL_bilabial_fricative": true,
            "VL_bilabial_plosive": true,
            "VL_dental_fricative": true,
            "VL_glottal_fricative": true,
            "VL_glottal_plosive": true,
            "VL_labiodental_fricative": true,
            "VL_palatal_fricative": true,
            "VL_palatal_plosive": true,
            "VL_pharyngeal_fricative": true,
            "VL_postalveolar_fricative": true,
            "VL_retroflex_fricative": true,
            "VL_retroflex_plosive": true,
            "VL_uvular_fricative": true,
            "VL_uvular_plosive": true,
            "VL_velar_fricative": true,
            "VL_velar_plosive": true
        },
        vowels: [
            { name: "close_back_rounded_vowel", include: true },
            { name: "close_back_unrounded_vowel", include: true },
            { name: "close_central_rounded_vowel", include: true },
            { name: "close_central_unrounded_vowel", include: true },
            { name: "close_front_rounded_vowel", include: true },
            { name: "close_front_unrounded_vowel", include: true },
            { name: "close-mid_back_rounded_vowel", include: true },
            { name: "close-mid_back_unrounded_vowel", include: true },
            { name: "close-mid_central_rounded_vowel", include: true },
            { name: "close-mid_central_unrounded_vowel", include: true },
            { name: "close-mid_front_rounded_vowel", include: true },
            { name: "close-mid_front_unrounded_vowel", include: true },
            { name: "mid-central_vowel", include: true },
            { name: "near-close_near-back_rounded_vowel", include: true },
            { name: "near-close_near-front_rounded_vowel", include: true },
            { name: "near-close_near-front_unrounded_vowel", include: true },
            { name: "near-open_central_unrounded_vowel", include: true },
            { name: "near-open_front_unrounded_vowel", include: true },
            { name: "open_back_rounded_vowel", include: true },
            { name: "open_back_unrounded_vowel", include: true },
            { name: "open_central_unrounded_vowel", include: true },
            { name: "open_front_rounded_vowel", include: true },
            { name: "open_front_unrounded_vowel", include: true },
            { name: "open-mid_back_rounded_vowel", include: true },
            { name: "open-mid_back_unrounded_vowel", include: true },
            { name: "open-mid_central_rounded_vowel", include: true },
            { name: "open-mid_central_unrounded_vowel", include: true },
            { name: "open-mid_front_rounded_vowel", include: true },
            { name: "open-mid_front_unrounded_vowel", include: true }
        ]
    },
    "haitian-creole": {
        consonants: {
            "V_alveolar_approximant": false,
            "V_alveolar_fricative": true,
            "V_alveolar_lateral_approximant": true,
            "V_alveolar_lateral_fricative": false,
            "V_alveolar_nasal": true,
            "V_alveolar_plosive": true,
            "V_alveolar_tap": false,
            "V_alveolar_trill": false,
            "V_bilabial_fricative": false,
            "V_bilabial_nasal": true,
            "V_bilabial_plosive": true,
            "V_bilabial_trill": false,
            "V_dental_fricative": false,
            "V_glottal_fricative": false,
            "V_labiodental_approximant": false,
            "V_labiodental_flap": false,
            "V_labiodental_fricative": true,
            "V_labiodental_nasal": false,
            "V_palatal_approximant": true,
            "V_palatal_fricative": false,
            "V_palatal_lateral_approximant": false,
            "V_palatal_nasal": false,
            "V_palatal_plosive": false,
            "V_pharyngeal_fricative": false,
            "V_postalveolar_fricative": true,
            "V_retroflex_approximant": false,
            "V_retroflex_flap": false,
            "V_retroflex_fricative": false,
            "V_retroflex_lateral approximant": false,
            "V_retroflex_nasal": false,
            "V_retroflex_plosive": false,
            "V_uvular_fricative": false,
            "V_uvular_nasal": false,
            "V_uvular_plosive": false,
            "V_uvular_trill": false,
            "V_velar_approximant": true,
            "V_velar_fricative": false,
            "V_velar_lateral_approximant": false,
            "V_velar_nasal": true,
            "V_velar_plosive": true,
            "VL_alveolar_fricative": true,
            "VL_alveolar_lateral_fricative": false,
            "VL_alveolar_plosive": true,
            "VL_bilabial_fricative": false,
            "VL_bilabial_plosive": true,
            "VL_dental_fricative": false,
            "VL_glottal_fricative": false,
            "VL_glottal_plosive": false,
            "VL_labiodental_fricative": true,
            "VL_palatal_fricative": false,
            "VL_palatal_plosive": false,
            "VL_pharyngeal_fricative": false,
            "VL_postalveolar_fricative": true,
            "VL_retroflex_fricative": false,
            "VL_retroflex_plosive": false,
            "VL_uvular_fricative": false,
            "VL_uvular_plosive": false,
            "VL_velar_fricative": false,
            "VL_velar_plosive": true
        },
        vowels: [
            { name: "close_back_rounded_vowel", include: true },
            { name: "close_back_unrounded_vowel", include: false },
            { name: "close_central_rounded_vowel", include: false },
            { name: "close_central_unrounded_vowel", include: false },
            { name: "close_front_rounded_vowel", include: false },
            { name: "close_front_unrounded_vowel", include: true },
            { name: "close-mid_back_rounded_vowel", include: true },
            { name: "close-mid_back_unrounded_vowel", include: false },
            { name: "close-mid_central_rounded_vowel", include: false },
            { name: "close-mid_central_unrounded_vowel", include: false },
            { name: "close-mid_front_rounded_vowel", include: false },
            { name: "close-mid_front_unrounded_vowel", include: true },
            { name: "mid-central_vowel", include: false },
            { name: "near-close_near-back_rounded_vowel", include: false },
            { name: "near-close_near-front_rounded_vowel", include: false },
            { name: "near-close_near-front_unrounded_vowel", include: false },
            { name: "near-open_central_unrounded_vowel", include: false },
            { name: "near-open_front_unrounded_vowel", include: false },
            { name: "open_back_rounded_vowel", include: false },
            { name: "open_back_unrounded_vowel", include: false },
            { name: "open_central_unrounded_vowel", include: false },
            { name: "open_front_rounded_vowel", include: false },
            { name: "open_front_unrounded_vowel", include: true },
            { name: "open-mid_back_rounded_vowel", include: true },
            { name: "open-mid_back_unrounded_vowel", include: false },
            { name: "open-mid_central_rounded_vowel", include: false },
            { name: "open-mid_central_unrounded_vowel", include: false },
            { name: "open-mid_front_rounded_vowel", include: false },
            { name: "open-mid_front_unrounded_vowel", include: true }
        ]
    },
    "general-american-english": {
        consonants: {},
        vowels: [
            { name: "close_back_rounded_vowel", include: true },
            { name: "close_back_unrounded_vowel", include: true },
            { name: "close_central_rounded_vowel", include: true },
            { name: "close_central_unrounded_vowel", include: true },
            { name: "close_front_rounded_vowel", include: true },
            { name: "close_front_unrounded_vowel", include: true },
            { name: "close-mid_back_rounded_vowel", include: true },
            { name: "close-mid_back_unrounded_vowel", include: true },
            { name: "close-mid_central_rounded_vowel", include: true },
            { name: "close-mid_central_unrounded_vowel", include: true },
            { name: "close-mid_front_rounded_vowel", include: true },
            { name: "close-mid_front_unrounded_vowel", include: true },
            { name: "mid-central_vowel", include: true },
            { name: "near-close_near-back_rounded_vowel", include: true },
            { name: "near-close_near-front_rounded_vowel", include: true },
            { name: "near-close_near-front_unrounded_vowel", include: true },
            { name: "near-open_central_unrounded_vowel", include: true },
            { name: "near-open_front_unrounded_vowel", include: true },
            { name: "open_back_rounded_vowel", include: true },
            { name: "open_back_unrounded_vowel", include: true },
            { name: "open_central_unrounded_vowel", include: true },
            { name: "open_front_rounded_vowel", include: true },
            { name: "open_front_unrounded_vowel", include: true },
            { name: "open-mid_back_rounded_vowel", include: true },
            { name: "open-mid_back_unrounded_vowel", include: true },
            { name: "open-mid_central_rounded_vowel", include: true },
            { name: "open-mid_central_unrounded_vowel", include: true },
            { name: "open-mid_front_rounded_vowel", include: true },
            { name: "open-mid_front_unrounded_vowel", include: true }
        ]
    },
    "french": {
        consonants: {},
        vowels: [
            { name: "close_back_rounded_vowel", include: true },
            { name: "close_back_unrounded_vowel", include: true },
            { name: "close_central_rounded_vowel", include: true },
            { name: "close_central_unrounded_vowel", include: true },
            { name: "close_front_rounded_vowel", include: true },
            { name: "close_front_unrounded_vowel", include: true },
            { name: "close-mid_back_rounded_vowel", include: true },
            { name: "close-mid_back_unrounded_vowel", include: true },
            { name: "close-mid_central_rounded_vowel", include: true },
            { name: "close-mid_central_unrounded_vowel", include: true },
            { name: "close-mid_front_rounded_vowel", include: true },
            { name: "close-mid_front_unrounded_vowel", include: true },
            { name: "mid-central_vowel", include: true },
            { name: "near-close_near-back_rounded_vowel", include: true },
            { name: "near-close_near-front_rounded_vowel", include: true },
            { name: "near-close_near-front_unrounded_vowel", include: true },
            { name: "near-open_central_unrounded_vowel", include: true },
            { name: "near-open_front_unrounded_vowel", include: true },
            { name: "open_back_rounded_vowel", include: true },
            { name: "open_back_unrounded_vowel", include: true },
            { name: "open_central_unrounded_vowel", include: true },
            { name: "open_front_rounded_vowel", include: true },
            { name: "open_front_unrounded_vowel", include: true },
            { name: "open-mid_back_rounded_vowel", include: true },
            { name: "open-mid_back_unrounded_vowel", include: true },
            { name: "open-mid_central_rounded_vowel", include: true },
            { name: "open-mid_central_unrounded_vowel", include: true },
            { name: "open-mid_front_rounded_vowel", include: true },
            { name: "open-mid_front_unrounded_vowel", include: true }
        ]
    },
    "icelandic": {
        consonants: {},
        vowels: [
            { name: "close_back_rounded_vowel", include: true },
            { name: "close_back_unrounded_vowel", include: true },
            { name: "close_central_rounded_vowel", include: true },
            { name: "close_central_unrounded_vowel", include: true },
            { name: "close_front_rounded_vowel", include: true },
            { name: "close_front_unrounded_vowel", include: true },
            { name: "close-mid_back_rounded_vowel", include: true },
            { name: "close-mid_back_unrounded_vowel", include: true },
            { name: "close-mid_central_rounded_vowel", include: true },
            { name: "close-mid_central_unrounded_vowel", include: true },
            { name: "close-mid_front_rounded_vowel", include: true },
            { name: "close-mid_front_unrounded_vowel", include: true },
            { name: "mid-central_vowel", include: true },
            { name: "near-close_near-back_rounded_vowel", include: true },
            { name: "near-close_near-front_rounded_vowel", include: true },
            { name: "near-close_near-front_unrounded_vowel", include: true },
            { name: "near-open_central_unrounded_vowel", include: true },
            { name: "near-open_front_unrounded_vowel", include: true },
            { name: "open_back_rounded_vowel", include: true },
            { name: "open_back_unrounded_vowel", include: true },
            { name: "open_central_unrounded_vowel", include: true },
            { name: "open_front_rounded_vowel", include: true },
            { name: "open_front_unrounded_vowel", include: true },
            { name: "open-mid_back_rounded_vowel", include: true },
            { name: "open-mid_back_unrounded_vowel", include: true },
            { name: "open-mid_central_rounded_vowel", include: true },
            { name: "open-mid_central_unrounded_vowel", include: true },
            { name: "open-mid_front_rounded_vowel", include: true },
            { name: "open-mid_front_unrounded_vowel", include: true }
        ]
    },
}

export {symbols, specs};