import Phone from "../components/IPAChart/phone";

let V_ALVEOLAR_APPROXIMANT = "V_alveolar_approximant";
let V_ALVEOLAR_FRICATIVE = "V_alveolar_fricative";
let V_ALVEOLAR_LATERAL_APPROXIMANT = "V_alveolar_lateral_approximant";
let V_ALVEOLAR_LATERAL_FRICATIVE = "V_alveolar_lateral_fricative";
let V_ALVEOLAR_NASAL = "V_alveolar_nasal";
let V_ALVEOLAR_PLOSIVE = "V_alveolar_plosive";
let V_ALVEOLAR_TAP = "V_alveolar_tap";
let V_ALVEOLAR_TRILL = "V_alveolar_trill";
let V_BILABIAL_FRICATIVE = "V_bilabial_fricative";
let V_BILABIAL_NASAL = "V_bilabial_nasal";
let V_BILABIAL_PLOSIVE = "V_bilabial_plosive";
let V_BILABIAL_TRILL = "V_bilabial_trill";
let V_DENTAL_FRICATIVE = "V_dental_fricative";
let V_DENTAL_LATERAL_APPROXIMANT = "V_dental_lateral_approximant";
let V_DENTAL_NASAL = "V_dental_nasal";
let V_GLOTTAL_FRICATIVE = "V_glottal_fricative";
let V_LABIODENTAL_APPROXIMANT = "V_labiodental_approximant";
let V_LABIODENTAL_FLAP = "V_labiodental_flap";
let V_LABIODENTAL_FRICATIVE = "V_labiodental_fricative";
let V_LABIODENTAL_NASAL = "V_labiodental_nasal";
let V_DENTAL_PLOSIVE = 'V_labiodental_plosive';
let V_PALATAL_APPROXIMANT = "V_palatal_approximant";
let V_PALATAL_FRICATIVE = "V_palatal_fricative";
let V_PALATAL_LATERAL_APPROXIMANT = "V_palatal_lateral_approximant";
let V_PALATAL_NASAL = "V_palatal_nasal";
let V_PALATAL_PLOSIVE = "V_palatal_plosive";
let V_PHARYNGEAL_FRICATIVE = "V_pharyngeal_fricative";
let V_POSTALVEOLAR_FRICATIVE = "V_postalveolar_fricative";
let V_RETROFLEX_APPROXIMANT = "V_retroflex_approximant";
let V_RETROFLEX_FLAP = "V_retroflex_flap";
let V_RETROFLEX_FRICATIVE = "V_retroflex_fricative";
let V_RETROFLEX_LATERAL_APPROXIMANT ="V_retroflex_lateral_approximant";
let V_RETROFLEX_NASAL = "V_retroflex_nasal";
let V_RETROFLEX_PLOSIVE = "V_retroflex_plosive";
let V_UVULAR_FRICATIVE = "V_uvular_fricative";
let V_UVULAR_NASAL = "V_uvular_nasal";
let V_UVULAR_PLOSIVE = "V_uvular_plosive";
let V_UVULAR_TRILL = "V_uvular_trill";
let V_VELAR_APPROXIMANT = "V_velar_approximant";
let V_VELAR_FRICATIVE = "V_velar_fricative";
let V_VELAR_LATERAL_APPROXIMANT = "V_velar_lateral_approximant";
let V_VELAR_NASAL = "V_velar_nasal";
let V_VELAR_PLOSIVE = "V_velar_plosive";
let VL_ALVEOLAR_FRICATIVE = "VL_alveolar_fricative";
let VL_ALVEOLAR_LATERAL_FRICATIVE = "VL_alveolar_lateral_fricative";
let VL_ALVEOLAR_PLOSIVE = "VL_alveolar_plosive";
let VL_BILABIAL_FRICATIVE = "VL_bilabial_fricative";
let VL_BILABIAL_PLOSIVE = "VL_bilabial_plosive";
let VL_DENTAL_FRICATIVE = "VL_dental_fricative";
let VL_GLOTTAL_FRICATIVE = "VL_glottal_fricative";
let VL_GLOTTAL_PLOSIVE = "VL_glottal_plosive";
let VL_LABIODENTAL_FRICATIVE = "VL_labiodental_fricative";
let VL_DENTAL_PLOSIVE = 'VL_labiodental_plosive';
let VL_PALATAL_FRICATIVE = "VL_palatal_fricative";
let VL_PALATAL_PLOSIVE = "VL_palatal_plosive";
let VL_PHARYNGEAL_FRICATIVE = "VL_pharyngeal_fricative";
let VL_POSTALVEOLAR_FRICATIVE = "VL_postalveolar_fricative";
let VL_RETROFLEX_FRICATIVE = "VL_retroflex_fricative";
let VL_RETROFLEX_PLOSIVE = "VL_retroflex_plosive";
let VL_UVULAR_FRICATIVE = "VL_uvular_fricative";
let VL_UVULAR_PLOSIVE = "VL_uvular_plosive";
let VL_VELAR_FRICATIVE = "VL_velar_fricative";
let VL_VELAR_PLOSIVE = "VL_velar_plosive";
let CLOSE_BACK_ROUNDED_VOWEL = 'close_back_rounded_vowel';
let CLOSE_BACK_UNROUNDED_VOWEL = 'close_back_unrounded_vowel';
let CLOSE_CENTRAL_ROUNDED_VOWEL = 'close_central_rounded_vowel';
let CLOSE_CENTRAL_UNROUNDED_VOWEL = 'close_central_unrounded_vowel';
let CLOSE_FRONT_ROUNDED_VOWEL = 'close_front_rounded_vowel';
let CLOSE_FRONT_UNROUNDED_VOWEL = 'close_front_unrounded_vowel';
let CLOSE_MID_BACK_ROUNDED_VOWEL ='close-mid_back_rounded_vowel';
let CLOSE_MID_BACK_UNROUNDED_VOWEL ='close-mid_back_unrounded_vowel';
let CLOSE_MID_CENTRAL_ROUNDED_VOWEL ='close-mid_central_rounded_vowel';
let CLOSE_MID_CENTRAL_UNROUNDED_VOWEL ='close-mid_central_unrounded_vowel';
let CLOSE_MID_FRONT_ROUNDED_VOWEL ='close-mid_front_rounded_vowel';
let CLOSE_MID_FRONT_UNROUNDED_VOWEL ='close-mid_front_unrounded_vowel';
let MID_CENTRAL_VOWEL ='mid-central_vowel';
let NEAR_CLOSE_NEAR_BACK_ROUNDED_VOWEL = 'near-close_near-back_rounded_vowel';
let NEAR_CLOSE_NEAR_FRONT_ROUNDED_VOWEL = 'near-close_near-front_rounded_vowel';
let NEAR_CLOSE_NEAR_FRONT_UNROUNDED_VOWEL = 'near-close_near-front_unrounded_vowel';
let NEAR_OPEN_CENTRAL_UNROUNDED_VOWEL ='near-open_central_unrounded_vowel';
let NEAR_OPEN_FRONT_UNROUNDED_VOWEL ='near-open_front_unrounded_vowel';
let OPEN_BACK_ROUNDED_VOWEL = 'open_back_rounded_vowel';
let OPEN_BACK_UNROUNDED_VOWEL = 'open_back_unrounded_vowel';
let OPEN_CENTRAL_UNROUNDED_VOWEL = 'open_central_unrounded_vowel';
let OPEN_FRONT_ROUNDED_VOWEL = 'open_front_rounded_vowel';
let OPEN_FRONT_UNROUNDED_VOWEL = 'open_front_unrounded_vowel';
let OPEN_MID_BACK_ROUNDED_VOWEL ='open-mid_back_rounded_vowel';
let OPEN_MID_BACK_UNROUNDED_VOWEL ='open-mid_back_unrounded_vowel';
let OPEN_MID_CENTRAL_ROUNDED_VOWEL ='open-mid_central_rounded_vowel';
let OPEN_MID_CENTRAL_UNROUNDED_VOWEL ='open-mid_central_unrounded_vowel';
let OPEN_MID_FRONT_ROUNDED_VOWEL ='open-mid_front_rounded_vowel';
let OPEN_MID_FRONT_UNROUNDED_VOWEL ='open-mid_front_unrounded_vowel';

let symbols = {
    consonants: {
        [V_ALVEOLAR_APPROXIMANT]: '',
        [V_ALVEOLAR_FRICATIVE]: '',
        [V_ALVEOLAR_LATERAL_APPROXIMANT]: '',
        [V_ALVEOLAR_LATERAL_FRICATIVE]: '',
        [V_ALVEOLAR_NASAL]: '',
        [V_ALVEOLAR_PLOSIVE]: '',
        [V_ALVEOLAR_TAP]: '',
        [V_ALVEOLAR_TRILL]: '',
        [V_BILABIAL_FRICATIVE]: '',
        [V_BILABIAL_NASAL]: '',
        [V_BILABIAL_PLOSIVE]: '',
        [V_BILABIAL_TRILL]: '',
        [V_DENTAL_FRICATIVE]: '',
        [V_GLOTTAL_FRICATIVE]: '',
        [V_LABIODENTAL_APPROXIMANT]: '',
        [V_LABIODENTAL_FLAP]: '',
        [V_LABIODENTAL_FRICATIVE]: '',
        [V_LABIODENTAL_NASAL]: '',
        [V_PALATAL_APPROXIMANT]: '',
        [V_PALATAL_FRICATIVE]: '',
        [V_PALATAL_LATERAL_APPROXIMANT]: '',
        [V_PALATAL_NASAL]: '',
        [V_PALATAL_PLOSIVE]: '',
        [V_PHARYNGEAL_FRICATIVE]: '',
        [V_POSTALVEOLAR_FRICATIVE]: '',
        [V_RETROFLEX_APPROXIMANT]: '',
        [V_RETROFLEX_FLAP]: '',
        [V_RETROFLEX_FRICATIVE]: '',
        [V_RETROFLEX_LATERAL_APPROXIMANT]: '',
        [V_RETROFLEX_NASAL]: '',
        [V_RETROFLEX_PLOSIVE]: '',
        [V_UVULAR_FRICATIVE]: '',
        [V_UVULAR_NASAL]: '',
        [V_UVULAR_PLOSIVE]: '',
        [V_UVULAR_TRILL]: '',
        [V_VELAR_APPROXIMANT]: '',
        [V_VELAR_FRICATIVE]: '',
        [V_VELAR_LATERAL_APPROXIMANT]: '',
        [V_VELAR_NASAL]: '',
        [V_VELAR_PLOSIVE]: '',
        [VL_ALVEOLAR_FRICATIVE]: '',
        [VL_ALVEOLAR_LATERAL_FRICATIVE]: '',
        [VL_ALVEOLAR_PLOSIVE]: '',
        [VL_BILABIAL_FRICATIVE]: '',
        [VL_BILABIAL_PLOSIVE]: '',
        [VL_DENTAL_FRICATIVE]: '',
        [VL_GLOTTAL_FRICATIVE]: '',
        [VL_GLOTTAL_PLOSIVE]: '',
        [VL_LABIODENTAL_FRICATIVE]: '',
        [VL_PALATAL_FRICATIVE]: '',
        [VL_PALATAL_PLOSIVE]: '',
        [VL_PHARYNGEAL_FRICATIVE]: '',
        [VL_POSTALVEOLAR_FRICATIVE]: '',
        [VL_RETROFLEX_FRICATIVE]: '',
        [VL_RETROFLEX_PLOSIVE]: '',
        [VL_UVULAR_FRICATIVE]: '',
        [VL_UVULAR_PLOSIVE]: '',
        [VL_VELAR_FRICATIVE]: '',
        [VL_VELAR_PLOSIVE]: '',
    },
    vowels: {
        [CLOSE_BACK_ROUNDED_VOWEL]: 'u',
        [CLOSE_BACK_UNROUNDED_VOWEL]: 'ɯ',
        [CLOSE_CENTRAL_ROUNDED_VOWEL]: 'ʉ',
        [CLOSE_CENTRAL_UNROUNDED_VOWEL]: 'ɨ',
        [CLOSE_FRONT_ROUNDED_VOWEL]: 'y',
        [CLOSE_FRONT_UNROUNDED_VOWEL]: 'i',
        [CLOSE_MID_BACK_ROUNDED_VOWEL]: 'o',
        [CLOSE_MID_BACK_UNROUNDED_VOWEL]: 'ɤ',
        [CLOSE_MID_CENTRAL_ROUNDED_VOWEL]: 'ɵ',
        [CLOSE_MID_CENTRAL_UNROUNDED_VOWEL]: 'ɘ',
        [CLOSE_MID_FRONT_ROUNDED_VOWEL]: 'ø',
        [CLOSE_MID_FRONT_UNROUNDED_VOWEL]: 'e',
        [MID_CENTRAL_VOWEL]: 'ə',
        [NEAR_CLOSE_NEAR_BACK_ROUNDED_VOWEL]: 'ʊ',
        [NEAR_CLOSE_NEAR_FRONT_ROUNDED_VOWEL]: 'ʏ',
        [NEAR_CLOSE_NEAR_FRONT_UNROUNDED_VOWEL]: 'ɪ',
        [NEAR_OPEN_CENTRAL_UNROUNDED_VOWEL]: 'ɐ',
        [NEAR_OPEN_FRONT_UNROUNDED_VOWEL]: 'æ',
        [OPEN_BACK_ROUNDED_VOWEL]: 'ɒ',
        [OPEN_BACK_UNROUNDED_VOWEL]: 'ɑ',
        [OPEN_CENTRAL_UNROUNDED_VOWEL]: 'ä',
        [OPEN_FRONT_ROUNDED_VOWEL]: 'ɶ',
        [OPEN_FRONT_UNROUNDED_VOWEL]: 'a',
        [OPEN_MID_BACK_ROUNDED_VOWEL]: 'ɔ',
        [OPEN_MID_BACK_UNROUNDED_VOWEL]: 'ʌ',
        [OPEN_MID_CENTRAL_ROUNDED_VOWEL]: 'ɞ',
        [OPEN_MID_CENTRAL_UNROUNDED_VOWEL]: 'ɜ',
        [OPEN_MID_FRONT_ROUNDED_VOWEL]: 'œ',
        [OPEN_MID_FRONT_UNROUNDED_VOWEL]: 'ɛ',
    }
};

let specs = {
    "test": {
        phonemes: [
            new Phone({consonant: true, bilabial: true, stop: true, aspirated: true, symbol: "pʰ"}),
            // new Phoneme(consonant = true, bilabial = true, weaklyaspirated = true),
            // new Phoneme(consonant = true, bilabial = true, unaspirated = true),
            new Phone({consonant: true, bilabial: true, stop: true, voiced: true, symbol: "b"}),
        ],
        consonants: {
            [V_ALVEOLAR_APPROXIMANT]: true,
            [V_BILABIAL_PLOSIVE]: true,
            [VL_BILABIAL_PLOSIVE]: true,
        },
        vowels: [{ name: [CLOSE_BACK_ROUNDED_VOWEL], include: true }],
    },
    "default": {
        phonemes: [
            new Phone({consonant: true, alveolar: true, approximant: true, voiced: true, symbol: "ɹ"}),
            new Phone({consonant: true, alveolar: true, fricative: true, voiced: true, symbol: "z"}),
            new Phone({consonant: true, alveolar: true, lateral: true, approximant: true, voiced: true, symbol: "l"}),
            new Phone({consonant: true, alveolar: true, lateral: true, fricative: true, voiced: true, symbol: "ɮ"}),
            new Phone({consonant: true, alveolar: true, nasal: true, voiced: true, symbol: "n"}),
            new Phone({consonant: true, alveolar: true, stop: true, voiced: true, symbol: "d"}),
            new Phone({consonant: true, alveolar: true, flap: true, voiced: true, symbol: "ɾ"}),
            new Phone({consonant: true, alveolar: true, trill: true, voiced: true, symbol: "r"}),
            new Phone({consonant: true, bilabial: true, fricative: true, voiced: true, symbol: "β"}),
            new Phone({consonant: true, bilabial: true, nasal: true, voiced: true, symbol: "m"}),
            new Phone({consonant: true, bilabial: true, stop: true, voiced: true, symbol: "b"}),
            new Phone({consonant: true, bilabial: true, trill: true, voiced: true, symbol: "ʙ"}),
            new Phone({consonant: true, dental: true, fricative: true, voiced: true, symbol: "ð"}),
            new Phone({consonant: true, laryngeal: true, fricative: true, voiced: true, symbol: "ɦ"}),
            new Phone({consonant: true, labiodental: true, approximant: true, voiced: true, symbol: "ʋ"}),
            new Phone({consonant: true, labiodental: true, flap: true, voiced: true, symbol: "ⱱ"}),
            new Phone({consonant: true, labiodental: true, fricative: true, voiced: true, symbol: "v"}),
            new Phone({consonant: true, labiodental: true, nasal: true, voiced: true, symbol: "ɱ"}),
            new Phone({consonant: true, palatal: true, approximant: true, voiced: true, symbol: "j"}),
            new Phone({consonant: true, palatal: true, fricative: true, voiced: true, symbol: "ʝ"}),
            new Phone({consonant: true, palatal: true, lateral: true, approximant: true, voiced: true, symbol: "ʎ"}),
            new Phone({consonant: true, palatal: true, nasal: true, voiced: true, symbol: "ɲ"}),
            new Phone({consonant: true, palatal: true, stop: true, voiced: true, symbol: "ɟ"}),
            new Phone({consonant: true, pharyngeal: true, fricative: true, voiced: true, symbol: "ʕ"}),
            new Phone({consonant: true, alveopalatal: true, fricative: true, voiced: true, symbol: "ʒ"}),
            new Phone({consonant: true, retroflex: true, approximant: true, voiced: true, symbol: "ɻ"}),
            new Phone({consonant: true, retroflex: true, flap: true, voiced: true, symbol: "ɽ"}),
            new Phone({consonant: true, retroflex: true, fricative: true, voiced: true, symbol: "ʐ"}),
            new Phone({consonant: true, retroflex: true, lateral: true, approximant: true, voiced: true, symbol: "ɭ"}),
            new Phone({consonant: true, retroflex: true, nasal: true, voiced: true, symbol: "ɳ"}),
            new Phone({consonant: true, retroflex: true, stop: true, voiced: true, symbol: "ɖ"}),
            new Phone({consonant: true, uvular: true, fricative: true, voiced: true, symbol: "ʁ"}),
            new Phone({consonant: true, uvular: true, nasal: true, voiced: true, symbol: "ɴ"}),
            new Phone({consonant: true, uvular: true, stop: true, voiced: true, symbol: "ɢ"}),
            new Phone({consonant: true, uvular: true, trill: true, voiced: true, symbol: "ʀ"}),
            new Phone({consonant: true, velar: true, approximant: true, voiced: true, symbol: "ɰ"}),
            new Phone({consonant: true, velar: true, fricative: true, voiced: true, symbol: "ɣ"}),
            new Phone({consonant: true, velar: true, lateral: true, approximant: true, voiced: true, symbol: "ʟ"}),
            new Phone({consonant: true, velar: true, nasal: true, voiced: true, symbol: "ŋ"}),
            new Phone({consonant: true, velar: true, nasal: true, voiced: true, symbol: "g"}),
            new Phone({consonant: true, alveolar: true, fricative: true, voiced: false, symbol: "s"}),
            new Phone({consonant: true, alveolar: true, lateral: true, fricative: true, voiced: false, symbol: "ɬ"}),
            new Phone({consonant: true, alveolar: true, stop: true, voiced: false, symbol: "t"}),
            new Phone({consonant: true, bilabial: true, fricative: true, voiced: false, symbol: "ɸ"}),
            new Phone({consonant: true, bilabial: true, stop: true, symbol: "p"}),
            new Phone({consonant: true, dental: true, fricative: true, voiced: false, symbol: "θ"}),
            new Phone({consonant: true, laryngeal: true, fricative: true, voiced: false, symbol: "h"}),
            new Phone({consonant: true, laryngeal: true, stop: true, voiced: false, symbol: "ʔ"}),
            new Phone({consonant: true, labiodental: true, fricative: true, voiced: false, symbol: "f"}),
            new Phone({consonant: true, palatal: true, fricative: true, voiced: false, symbol: "ç"}),
            new Phone({consonant: true, palatal: true, stop: true, voiced: false, symbol: "c"}),
            new Phone({consonant: true, pharyngeal: true, fricative: true, voiced: false, symbol: "ħ"}),
            new Phone({consonant: true, alveopalatal: true, fricative: true, voiced: false, symbol: "ʃ"}),
            new Phone({consonant: true, retroflex: true, fricative: true, voiced: false, symbol: "ʂ"}),
            new Phone({consonant: true, retroflex: true, stop: true, voiced: false, symbol: "ʈ"}),
            new Phone({consonant: true, uvular: true, fricative: true, voiced: false, symbol: "χ"}),
            new Phone({consonant: true, uvular: true, stop: true, voiced: false, symbol: "q"}),
            new Phone({consonant: true, velar: true, fricative: true, voiced: false, symbol: "x"}),
            new Phone({consonant: true, velar: true, stop: true, voiced: false, symbol: "k"}),
        ],
        consonants: {
            [V_ALVEOLAR_APPROXIMANT]: true,
            [V_ALVEOLAR_FRICATIVE]: true,
            [V_ALVEOLAR_LATERAL_APPROXIMANT]: true,
            [V_ALVEOLAR_LATERAL_FRICATIVE]: true,
            [V_ALVEOLAR_NASAL]: true,
            [V_ALVEOLAR_PLOSIVE]: true,
            [V_ALVEOLAR_TAP]: true,
            [V_ALVEOLAR_TRILL]: true,
            [V_BILABIAL_FRICATIVE]: true,
            [V_BILABIAL_NASAL]: true,
            [V_BILABIAL_PLOSIVE]: true,
            [V_BILABIAL_TRILL]: true,
            [V_DENTAL_FRICATIVE]: true,
            [V_GLOTTAL_FRICATIVE]: true,
            [V_LABIODENTAL_APPROXIMANT]: true,
            [V_LABIODENTAL_FLAP]: true,
            [V_LABIODENTAL_FRICATIVE]: true,
            [V_LABIODENTAL_NASAL]: true,
            [V_PALATAL_APPROXIMANT]: true,
            [V_PALATAL_FRICATIVE]: true,
            [V_PALATAL_LATERAL_APPROXIMANT]: true,
            [V_PALATAL_NASAL]: true,
            [V_PALATAL_PLOSIVE]: true,
            [V_PHARYNGEAL_FRICATIVE]: true,
            [V_POSTALVEOLAR_FRICATIVE]: true,
            [V_RETROFLEX_APPROXIMANT]: true,
            [V_RETROFLEX_FLAP]: true,
            [V_RETROFLEX_FRICATIVE]: true,
            [V_RETROFLEX_LATERAL_APPROXIMANT]: true,
            [V_RETROFLEX_NASAL]: true,
            [V_RETROFLEX_PLOSIVE]: true,
            [V_UVULAR_FRICATIVE]: true,
            [V_UVULAR_NASAL]: true,
            [V_UVULAR_PLOSIVE]: true,
            [V_UVULAR_TRILL]: true,
            [V_VELAR_APPROXIMANT]: true,
            [V_VELAR_FRICATIVE]: true,
            [V_VELAR_LATERAL_APPROXIMANT]: true,
            [V_VELAR_NASAL]: true,
            [V_VELAR_PLOSIVE]: true,
            [VL_ALVEOLAR_FRICATIVE]: true,
            [VL_ALVEOLAR_LATERAL_FRICATIVE]: true,
            [VL_ALVEOLAR_PLOSIVE]: true,
            [VL_BILABIAL_FRICATIVE]: true,
            [VL_BILABIAL_PLOSIVE]: true,
            [VL_DENTAL_FRICATIVE]: true,
            [VL_GLOTTAL_FRICATIVE]: true,
            [VL_GLOTTAL_PLOSIVE]: true,
            [VL_LABIODENTAL_FRICATIVE]: true,
            [VL_PALATAL_FRICATIVE]: true,
            [VL_PALATAL_PLOSIVE]: true,
            [VL_PHARYNGEAL_FRICATIVE]: true,
            [VL_POSTALVEOLAR_FRICATIVE]: true,
            [VL_RETROFLEX_FRICATIVE]: true,
            [VL_RETROFLEX_PLOSIVE]: true,
            [VL_UVULAR_FRICATIVE]: true,
            [VL_UVULAR_PLOSIVE]: true,
            [VL_VELAR_FRICATIVE]: true,
            [VL_VELAR_PLOSIVE]: true
        },
        vowels: [
            { name: [CLOSE_BACK_ROUNDED_VOWEL], include: true },
            { name: [CLOSE_BACK_UNROUNDED_VOWEL], include: true },
            { name: [CLOSE_CENTRAL_ROUNDED_VOWEL], include: true },
            { name: [CLOSE_CENTRAL_UNROUNDED_VOWEL], include: true },
            { name: [CLOSE_FRONT_ROUNDED_VOWEL], include: true },
            { name: [CLOSE_FRONT_UNROUNDED_VOWEL], include: true },
            { name: [CLOSE_MID_BACK_ROUNDED_VOWEL], include: true },
            { name: [CLOSE_MID_BACK_UNROUNDED_VOWEL], include: true },
            { name: [CLOSE_MID_CENTRAL_ROUNDED_VOWEL], include: true },
            { name: [CLOSE_MID_CENTRAL_UNROUNDED_VOWEL], include: true },
            { name: [CLOSE_MID_FRONT_ROUNDED_VOWEL], include: true },
            { name: [CLOSE_MID_FRONT_UNROUNDED_VOWEL], include: true },
            { name: [MID_CENTRAL_VOWEL], include: true },
            { name: [NEAR_CLOSE_NEAR_BACK_ROUNDED_VOWEL], include: true },
            { name: [NEAR_CLOSE_NEAR_FRONT_ROUNDED_VOWEL], include: true },
            { name: [NEAR_CLOSE_NEAR_FRONT_UNROUNDED_VOWEL], include: true },
            { name: [NEAR_OPEN_CENTRAL_UNROUNDED_VOWEL], include: true },
            { name: [NEAR_OPEN_FRONT_UNROUNDED_VOWEL], include: true },
            { name: [OPEN_BACK_ROUNDED_VOWEL], include: true },
            { name: [OPEN_BACK_UNROUNDED_VOWEL], include: true },
            { name: [OPEN_CENTRAL_UNROUNDED_VOWEL], include: true },
            { name: [OPEN_FRONT_ROUNDED_VOWEL], include: true },
            { name: [OPEN_FRONT_UNROUNDED_VOWEL], include: true },
            { name: [OPEN_MID_BACK_ROUNDED_VOWEL], include: true },
            { name: [OPEN_MID_BACK_UNROUNDED_VOWEL], include: true },
            { name: [OPEN_MID_CENTRAL_ROUNDED_VOWEL], include: true },
            { name: [OPEN_MID_CENTRAL_UNROUNDED_VOWEL], include: true },
            { name: [OPEN_MID_FRONT_ROUNDED_VOWEL], include: true },
            { name: [OPEN_MID_FRONT_UNROUNDED_VOWEL], include: true }
        ]
    },
    "haitian-creole": {
        consonants: {
            [V_ALVEOLAR_APPROXIMANT]: false,
            [V_ALVEOLAR_FRICATIVE]: true,
            [V_ALVEOLAR_LATERAL_APPROXIMANT]: true,
            [V_ALVEOLAR_LATERAL_FRICATIVE]: false,
            [V_ALVEOLAR_NASAL]: true,
            [V_ALVEOLAR_PLOSIVE]: true,
            [V_ALVEOLAR_TAP]: false,
            [V_ALVEOLAR_TRILL]: false,
            [V_BILABIAL_FRICATIVE]: false,
            [V_BILABIAL_NASAL]: true,
            [V_BILABIAL_PLOSIVE]: true,
            [V_BILABIAL_TRILL]: false,
            [V_DENTAL_FRICATIVE]: false,
            [V_GLOTTAL_FRICATIVE]: false,
            [V_LABIODENTAL_APPROXIMANT]: false,
            [V_LABIODENTAL_FLAP]: false,
            [V_LABIODENTAL_FRICATIVE]: true,
            [V_LABIODENTAL_NASAL]: false,
            [V_PALATAL_APPROXIMANT]: true,
            [V_PALATAL_FRICATIVE]: false,
            [V_PALATAL_LATERAL_APPROXIMANT]: false,
            [V_PALATAL_NASAL]: false,
            [V_PALATAL_PLOSIVE]: false,
            [V_PHARYNGEAL_FRICATIVE]: false,
            [V_POSTALVEOLAR_FRICATIVE]: true,
            [V_RETROFLEX_APPROXIMANT]: false,
            [V_RETROFLEX_FLAP]: false,
            [V_RETROFLEX_FRICATIVE]: false,
            [V_RETROFLEX_LATERAL_APPROXIMANT]: false,
            [V_RETROFLEX_NASAL]: false,
            [V_RETROFLEX_PLOSIVE]: false,
            [V_UVULAR_FRICATIVE]: false,
            [V_UVULAR_NASAL]: false,
            [V_UVULAR_PLOSIVE]: false,
            [V_UVULAR_TRILL]: false,
            [V_VELAR_APPROXIMANT]: true,
            [V_VELAR_FRICATIVE]: false,
            [V_VELAR_LATERAL_APPROXIMANT]: false,
            [V_VELAR_NASAL]: true,
            [V_VELAR_PLOSIVE]: true,
            [VL_ALVEOLAR_FRICATIVE]: true,
            [VL_ALVEOLAR_LATERAL_FRICATIVE]: false,
            [VL_ALVEOLAR_PLOSIVE]: true,
            [VL_BILABIAL_FRICATIVE]: false,
            [VL_BILABIAL_PLOSIVE]: true,
            [VL_DENTAL_FRICATIVE]: false,
            [VL_GLOTTAL_FRICATIVE]: false,
            [VL_GLOTTAL_PLOSIVE]: false,
            [VL_LABIODENTAL_FRICATIVE]: true,
            [VL_PALATAL_FRICATIVE]: false,
            [VL_PALATAL_PLOSIVE]: false,
            [VL_PHARYNGEAL_FRICATIVE]: false,
            [VL_POSTALVEOLAR_FRICATIVE]: true,
            [VL_RETROFLEX_FRICATIVE]: false,
            [VL_RETROFLEX_PLOSIVE]: false,
            [VL_UVULAR_FRICATIVE]: false,
            [VL_UVULAR_PLOSIVE]: false,
            [VL_VELAR_FRICATIVE]: false,
            [VL_VELAR_PLOSIVE]: true,
        },
        vowels: [
            { name: [CLOSE_BACK_ROUNDED_VOWEL], include: true },
            { name: [CLOSE_BACK_UNROUNDED_VOWEL], include: false },
            { name: [CLOSE_CENTRAL_ROUNDED_VOWEL], include: false },
            { name: [CLOSE_CENTRAL_UNROUNDED_VOWEL], include: false },
            { name: [CLOSE_FRONT_ROUNDED_VOWEL], include: false },
            { name: [CLOSE_FRONT_UNROUNDED_VOWEL], include: true },
            { name: [CLOSE_MID_BACK_ROUNDED_VOWEL], include: true },
            { name: [CLOSE_MID_BACK_UNROUNDED_VOWEL], include: false },
            { name: [CLOSE_MID_CENTRAL_ROUNDED_VOWEL], include: false },
            { name: [CLOSE_MID_CENTRAL_UNROUNDED_VOWEL], include: false },
            { name: [CLOSE_MID_FRONT_ROUNDED_VOWEL], include: false },
            { name: [CLOSE_MID_FRONT_UNROUNDED_VOWEL], include: true },
            { name: [MID_CENTRAL_VOWEL], include: false },
            { name: [NEAR_CLOSE_NEAR_BACK_ROUNDED_VOWEL], include: false },
            { name: [NEAR_CLOSE_NEAR_FRONT_ROUNDED_VOWEL], include: false },
            { name: [NEAR_CLOSE_NEAR_FRONT_UNROUNDED_VOWEL], include: false },
            { name: [NEAR_OPEN_CENTRAL_UNROUNDED_VOWEL], include: false },
            { name: [NEAR_OPEN_FRONT_UNROUNDED_VOWEL], include: false },
            { name: [OPEN_BACK_ROUNDED_VOWEL], include: false },
            { name: [OPEN_BACK_UNROUNDED_VOWEL], include: false },
            { name: [OPEN_CENTRAL_UNROUNDED_VOWEL], include: false },
            { name: [OPEN_FRONT_ROUNDED_VOWEL], include: false },
            { name: [OPEN_FRONT_UNROUNDED_VOWEL], include: true },
            { name: [OPEN_MID_BACK_ROUNDED_VOWEL], include: true },
            { name: [OPEN_MID_BACK_UNROUNDED_VOWEL], include: false },
            { name: [OPEN_MID_CENTRAL_ROUNDED_VOWEL], include: false },
            { name: [OPEN_MID_CENTRAL_UNROUNDED_VOWEL], include: false },
            { name: [OPEN_MID_FRONT_ROUNDED_VOWEL], include: false },
            { name: [OPEN_MID_FRONT_UNROUNDED_VOWEL], include: true }
        ]
    },
    "general-american-english": {
        consonants: {
            [V_ALVEOLAR_APPROXIMANT]: true,
            [V_ALVEOLAR_FRICATIVE]: true,
            [V_ALVEOLAR_LATERAL_APPROXIMANT]: true,
            [V_ALVEOLAR_LATERAL_FRICATIVE]: false,
            [V_ALVEOLAR_NASAL]: true,
            [V_ALVEOLAR_PLOSIVE]: true,
            [V_ALVEOLAR_TAP]: false,
            [V_ALVEOLAR_TRILL]: false,
            [V_BILABIAL_FRICATIVE]: false,
            [V_BILABIAL_NASAL]: true,
            [V_BILABIAL_PLOSIVE]: true,
            [V_BILABIAL_TRILL]: false,
            [V_DENTAL_FRICATIVE]: true,
            [V_GLOTTAL_FRICATIVE]: false,
            [V_LABIODENTAL_APPROXIMANT]: false,
            [V_LABIODENTAL_FLAP]: false,
            [V_LABIODENTAL_FRICATIVE]: true,
            [V_LABIODENTAL_NASAL]: false,
            [V_PALATAL_APPROXIMANT]: true,
            [V_PALATAL_FRICATIVE]: false,
            [V_PALATAL_LATERAL_APPROXIMANT]: false,
            [V_PALATAL_NASAL]: false,
            [V_PALATAL_PLOSIVE]: false,
            [V_PHARYNGEAL_FRICATIVE]: false,
            [V_POSTALVEOLAR_FRICATIVE]: true,
            [V_RETROFLEX_APPROXIMANT]: false,
            [V_RETROFLEX_FLAP]: false,
            [V_RETROFLEX_FRICATIVE]: false,
            [V_RETROFLEX_LATERAL_APPROXIMANT]: false,
            [V_RETROFLEX_NASAL]: false,
            [V_RETROFLEX_PLOSIVE]: false,
            [V_UVULAR_FRICATIVE]: false,
            [V_UVULAR_NASAL]: false,
            [V_UVULAR_PLOSIVE]: false,
            [V_UVULAR_TRILL]: false,
            [V_VELAR_APPROXIMANT]: false,
            [V_VELAR_FRICATIVE]: false,
            [V_VELAR_LATERAL_APPROXIMANT]: false,
            [V_VELAR_NASAL]: true,
            [V_VELAR_PLOSIVE]: true,
            [VL_ALVEOLAR_FRICATIVE]: true,
            [VL_ALVEOLAR_LATERAL_FRICATIVE]: false,
            [VL_ALVEOLAR_PLOSIVE]: true,
            [VL_BILABIAL_FRICATIVE]: false,
            [VL_BILABIAL_PLOSIVE]: true,
            [VL_DENTAL_FRICATIVE]: true,
            [VL_GLOTTAL_FRICATIVE]: true,
            [VL_GLOTTAL_PLOSIVE]: false,
            [VL_LABIODENTAL_FRICATIVE]: true,
            [VL_PALATAL_FRICATIVE]: false,
            [VL_PALATAL_PLOSIVE]: false,
            [VL_PHARYNGEAL_FRICATIVE]: false,
            [VL_POSTALVEOLAR_FRICATIVE]: true,
            [VL_RETROFLEX_FRICATIVE]: false,
            [VL_RETROFLEX_PLOSIVE]: false,
            [VL_UVULAR_FRICATIVE]: false,
            [VL_UVULAR_PLOSIVE]: false,
            [VL_VELAR_FRICATIVE]: false,
            [VL_VELAR_PLOSIVE]: true
        },
        vowels: [
            { name: "close_back_rounded_vowel", include: true },
            { name: "close_back_unrounded_vowel", include: false },
            { name: "close_central_rounded_vowel", include: false },
            { name: "close_central_unrounded_vowel", include: false },
            { name: "close_front_rounded_vowel", include: false },
            { name: "close_front_unrounded_vowel", include: true },
            { name: "close-mid_back_rounded_vowel", include: true },
            { name: "close-mid_back_unrounded_vowel", include: false },
            { name: "close-mid_central_rounded_vowel", include: false },
            { name: "close-mid_central_unrounded_vowel", include: false },
            { name: "close-mid_front_rounded_vowel", include: false },
            { name: "close-mid_front_unrounded_vowel", include: true },
            { name: "mid-central_vowel", include: true },
            { name: "near-close_near-back_rounded_vowel", include: true },
            { name: "near-close_near-front_rounded_vowel", include: false },
            { name: "near-close_near-front_unrounded_vowel", include: true },
            { name: "near-open_central_unrounded_vowel", include: false },
            { name: "near-open_front_unrounded_vowel", include: true },
            { name: "open_back_rounded_vowel", include: false },
            { name: "open_back_unrounded_vowel", include: true },
            { name: "open_central_unrounded_vowel", include: false },
            { name: "open_front_rounded_vowel", include: false },
            { name: "open_front_unrounded_vowel", include: false },
            { name: "open-mid_back_rounded_vowel", include: true },
            { name: "open-mid_back_unrounded_vowel", include: true },
            { name: "open-mid_central_rounded_vowel", include: false },
            { name: "open-mid_central_unrounded_vowel", include: false },
            { name: "open-mid_front_rounded_vowel", include: false },
            { name: "open-mid_front_unrounded_vowel", include: true }
        ]
    },
    "french": {
        consonants: {
            [V_ALVEOLAR_APPROXIMANT]: true,
            [V_ALVEOLAR_FRICATIVE]: true,
            [V_ALVEOLAR_LATERAL_APPROXIMANT]: true,
            [V_ALVEOLAR_LATERAL_FRICATIVE]: true,
            [V_ALVEOLAR_NASAL]: true,
            [V_ALVEOLAR_PLOSIVE]: true,
            [V_ALVEOLAR_TAP]: true,
            [V_ALVEOLAR_TRILL]: true,
            [V_BILABIAL_FRICATIVE]: true,
            [V_BILABIAL_NASAL]: true,
            [V_BILABIAL_PLOSIVE]: true,
            [V_BILABIAL_TRILL]: true,
            [V_DENTAL_FRICATIVE]: true,
            [V_GLOTTAL_FRICATIVE]: true,
            [V_LABIODENTAL_APPROXIMANT]: true,
            [V_LABIODENTAL_FLAP]: true,
            [V_LABIODENTAL_FRICATIVE]: true,
            [V_LABIODENTAL_NASAL]: true,
            [V_PALATAL_APPROXIMANT]: true,
            [V_PALATAL_FRICATIVE]: true,
            [V_PALATAL_LATERAL_APPROXIMANT]: true,
            [V_PALATAL_NASAL]: true,
            [V_PALATAL_PLOSIVE]: true,
            [V_PHARYNGEAL_FRICATIVE]: true,
            [V_POSTALVEOLAR_FRICATIVE]: true,
            [V_RETROFLEX_APPROXIMANT]: true,
            [V_RETROFLEX_FLAP]: true,
            [V_RETROFLEX_FRICATIVE]: true,
            [V_RETROFLEX_LATERAL_APPROXIMANT]: true,
            [V_RETROFLEX_NASAL]: true,
            [V_RETROFLEX_PLOSIVE]: true,
            [V_UVULAR_FRICATIVE]: true,
            [V_UVULAR_NASAL]: true,
            [V_UVULAR_PLOSIVE]: true,
            [V_UVULAR_TRILL]: true,
            [V_VELAR_APPROXIMANT]: true,
            [V_VELAR_FRICATIVE]: true,
            [V_VELAR_LATERAL_APPROXIMANT]: true,
            [V_VELAR_NASAL]: true,
            [V_VELAR_PLOSIVE]: true,
            [VL_ALVEOLAR_FRICATIVE]: true,
            [VL_ALVEOLAR_LATERAL_FRICATIVE]: true,
            [VL_ALVEOLAR_PLOSIVE]: true,
            [VL_BILABIAL_FRICATIVE]: true,
            [VL_BILABIAL_PLOSIVE]: true,
            [VL_DENTAL_FRICATIVE]: true,
            [VL_GLOTTAL_FRICATIVE]: true,
            [VL_GLOTTAL_PLOSIVE]: true,
            [VL_LABIODENTAL_FRICATIVE]: true,
            [VL_PALATAL_FRICATIVE]: true,
            [VL_PALATAL_PLOSIVE]: true,
            [VL_PHARYNGEAL_FRICATIVE]: true,
            [VL_POSTALVEOLAR_FRICATIVE]: true,
            [VL_RETROFLEX_FRICATIVE]: true,
            [VL_RETROFLEX_PLOSIVE]: true,
            [VL_UVULAR_FRICATIVE]: true,
            [VL_UVULAR_PLOSIVE]: true,
            [VL_VELAR_FRICATIVE]: true,
            [VL_VELAR_PLOSIVE]: true
        },
        vowels: [
            { name: "close_back_rounded_vowel", include: true },
            { name: "close_back_unrounded_vowel", include: true },
            { name: "close_central_rounded_vowel", include: true },
            { name: "close_central_unrounded_vowel", include: true },
            { name: "close_front_rounded_vowel", include: true },
            { name: "close_front_unrounded_vowel", include: true },
            { name: "close-mid_back_rounded_vowel", include: true },
            { name: "close-mid_back_unrounded_vowel", include: true },
            { name: "close-mid_central_rounded_vowel", include: true },
            { name: "close-mid_central_unrounded_vowel", include: true },
            { name: "close-mid_front_rounded_vowel", include: true },
            { name: "close-mid_front_unrounded_vowel", include: true },
            { name: "mid-central_vowel", include: true },
            { name: "near-close_near-back_rounded_vowel", include: true },
            { name: "near-close_near-front_rounded_vowel", include: true },
            { name: "near-close_near-front_unrounded_vowel", include: true },
            { name: "near-open_central_unrounded_vowel", include: true },
            { name: "near-open_front_unrounded_vowel", include: true },
            { name: "open_back_rounded_vowel", include: true },
            { name: "open_back_unrounded_vowel", include: true },
            { name: "open_central_unrounded_vowel", include: true },
            { name: "open_front_rounded_vowel", include: true },
            { name: "open_front_unrounded_vowel", include: true },
            { name: "open-mid_back_rounded_vowel", include: true },
            { name: "open-mid_back_unrounded_vowel", include: true },
            { name: "open-mid_central_rounded_vowel", include: true },
            { name: "open-mid_central_unrounded_vowel", include: true },
            { name: "open-mid_front_rounded_vowel", include: true },
            { name: "open-mid_front_unrounded_vowel", include: true }
        ]
    },
    "icelandic": {
        consonants: {
            [V_ALVEOLAR_APPROXIMANT]: true,
            [V_ALVEOLAR_FRICATIVE]: true,
            [V_ALVEOLAR_LATERAL_APPROXIMANT]: true,
            [V_ALVEOLAR_LATERAL_FRICATIVE]: true,
            [V_ALVEOLAR_NASAL]: true,
            [V_ALVEOLAR_PLOSIVE]: true,
            [V_ALVEOLAR_TAP]: true,
            [V_ALVEOLAR_TRILL]: true,
            [V_BILABIAL_FRICATIVE]: true,
            [V_BILABIAL_NASAL]: true,
            [V_BILABIAL_PLOSIVE]: true,
            [V_BILABIAL_TRILL]: true,
            [V_DENTAL_FRICATIVE]: true,
            [V_GLOTTAL_FRICATIVE]: true,
            [V_LABIODENTAL_APPROXIMANT]: true,
            [V_LABIODENTAL_FLAP]: true,
            [V_LABIODENTAL_FRICATIVE]: true,
            [V_LABIODENTAL_NASAL]: true,
            [V_PALATAL_APPROXIMANT]: true,
            [V_PALATAL_FRICATIVE]: true,
            [V_PALATAL_LATERAL_APPROXIMANT]: true,
            [V_PALATAL_NASAL]: true,
            [V_PALATAL_PLOSIVE]: true,
            [V_PHARYNGEAL_FRICATIVE]: true,
            [V_POSTALVEOLAR_FRICATIVE]: true,
            [V_RETROFLEX_APPROXIMANT]: true,
            [V_RETROFLEX_FLAP]: true,
            [V_RETROFLEX_FRICATIVE]: true,
            [V_RETROFLEX_LATERAL_APPROXIMANT]: true,
            [V_RETROFLEX_NASAL]: true,
            [V_RETROFLEX_PLOSIVE]: true,
            [V_UVULAR_FRICATIVE]: true,
            [V_UVULAR_NASAL]: true,
            [V_UVULAR_PLOSIVE]: true,
            [V_UVULAR_TRILL]: true,
            [V_VELAR_APPROXIMANT]: true,
            [V_VELAR_FRICATIVE]: true,
            [V_VELAR_LATERAL_APPROXIMANT]: true,
            [V_VELAR_NASAL]: true,
            [V_VELAR_PLOSIVE]: true,
            [VL_ALVEOLAR_FRICATIVE]: true,
            [VL_ALVEOLAR_LATERAL_FRICATIVE]: true,
            [VL_ALVEOLAR_PLOSIVE]: true,
            [VL_BILABIAL_FRICATIVE]: true,
            [VL_BILABIAL_PLOSIVE]: true,
            [VL_DENTAL_FRICATIVE]: true,
            [VL_GLOTTAL_FRICATIVE]: true,
            [VL_GLOTTAL_PLOSIVE]: true,
            [VL_LABIODENTAL_FRICATIVE]: true,
            [VL_PALATAL_FRICATIVE]: true,
            [VL_PALATAL_PLOSIVE]: true,
            [VL_PHARYNGEAL_FRICATIVE]: true,
            [VL_POSTALVEOLAR_FRICATIVE]: true,
            [VL_RETROFLEX_FRICATIVE]: true,
            [VL_RETROFLEX_PLOSIVE]: true,
            [VL_UVULAR_FRICATIVE]: true,
            [VL_UVULAR_PLOSIVE]: true,
            [VL_VELAR_FRICATIVE]: true,
            [VL_VELAR_PLOSIVE]: true
        },
        vowels: [
            { name: "close_back_rounded_vowel", include: true },
            { name: "close_back_unrounded_vowel", include: false },
            { name: "close_central_rounded_vowel", include: false },
            { name: "close_central_unrounded_vowel", include: false },
            { name: "close_front_rounded_vowel", include: false },
            { name: "close_front_unrounded_vowel", include: true },
            { name: "close-mid_back_rounded_vowel", include: false },
            { name: "close-mid_back_unrounded_vowel", include: false },
            { name: "close-mid_central_rounded_vowel", include: false },
            { name: "close-mid_central_unrounded_vowel", include: false },
            { name: "close-mid_front_rounded_vowel", include: false },
            { name: "close-mid_front_unrounded_vowel", include: false },
            { name: "mid-central_vowel", include: false },
            { name: "near-close_near-back_rounded_vowel", include: false },
            { name: "near-close_near-front_rounded_vowel", include: true },
            { name: "near-close_near-front_unrounded_vowel", include: true },
            { name: "near-open_central_unrounded_vowel", include: false },
            { name: "near-open_front_unrounded_vowel", include: false },
            { name: "open_back_rounded_vowel", include: false },
            { name: "open_back_unrounded_vowel", include: false },
            { name: "open_central_unrounded_vowel", include: false },
            { name: "open_front_rounded_vowel", include: false },
            { name: "open_front_unrounded_vowel", include: true },
            { name: "open-mid_back_rounded_vowel", include: true },
            { name: "open-mid_back_unrounded_vowel", include: false },
            { name: "open-mid_central_rounded_vowel", include: false },
            { name: "open-mid_central_unrounded_vowel", include: false },
            { name: "open-mid_front_rounded_vowel", include: true },
            { name: "open-mid_front_unrounded_vowel", include: true }
        ]
    },
    "spanish": {
        phonemes: [],
        consonants: {
            [VL_BILABIAL_PLOSIVE]: true,
            [V_BILABIAL_PLOSIVE]: true,
            [V_BILABIAL_NASAL]: true,
            [V_DENTAL_NASAL]: true,
            [V_DENTAL_LATERAL_APPROXIMANT]: true,
            [VL_LABIODENTAL_FRICATIVE]: true,
            [VL_DENTAL_PLOSIVE]: true,
            [V_DENTAL_PLOSIVE]: true,
            [V_ALVEOLAR_TAP]: true,
            [VL_ALVEOLAR_FRICATIVE]: true,
            [V_ALVEOLAR_TRILL]: true,
            [V_PALATAL_NASAL]: true,
            [V_PALATAL_FRICATIVE]: true,
            [VL_VELAR_PLOSIVE]: true,
            [V_VELAR_PLOSIVE]: true,
            [VL_VELAR_FRICATIVE]: true,
        },
        vowels: [
            { name: [CLOSE_BACK_ROUNDED_VOWEL], include: true },
            { name: [CLOSE_BACK_UNROUNDED_VOWEL], include: false },
            { name: [CLOSE_CENTRAL_ROUNDED_VOWEL], include: false },
            { name: [CLOSE_CENTRAL_UNROUNDED_VOWEL], include: false },
            { name: [CLOSE_FRONT_ROUNDED_VOWEL], include: false },
            { name: [CLOSE_FRONT_UNROUNDED_VOWEL], include: true },
            { name: [CLOSE_MID_BACK_ROUNDED_VOWEL], include: true },
            { name: [CLOSE_MID_BACK_UNROUNDED_VOWEL], include: false },
            { name: [CLOSE_MID_CENTRAL_ROUNDED_VOWEL], include: false },
            { name: [CLOSE_MID_CENTRAL_UNROUNDED_VOWEL], include: false },
            { name: [CLOSE_MID_FRONT_ROUNDED_VOWEL], include: false },
            { name: [CLOSE_MID_FRONT_UNROUNDED_VOWEL], include: true },
            { name: [MID_CENTRAL_VOWEL], include: false },
            { name: [NEAR_CLOSE_NEAR_BACK_ROUNDED_VOWEL], include: false },
            { name: [NEAR_CLOSE_NEAR_FRONT_ROUNDED_VOWEL], include: false },
            { name: [NEAR_CLOSE_NEAR_FRONT_UNROUNDED_VOWEL], include: false },
            { name: [NEAR_OPEN_CENTRAL_UNROUNDED_VOWEL], include: false },
            { name: [NEAR_OPEN_FRONT_UNROUNDED_VOWEL], include: false },
            { name: [OPEN_BACK_ROUNDED_VOWEL], include: false },
            { name: [OPEN_BACK_UNROUNDED_VOWEL], include: false },
            { name: [OPEN_CENTRAL_UNROUNDED_VOWEL], include: true },
            { name: [OPEN_FRONT_ROUNDED_VOWEL], include: false },
            { name: [OPEN_FRONT_UNROUNDED_VOWEL], include: false },
            { name: [OPEN_MID_BACK_ROUNDED_VOWEL], include: false },
            { name: [OPEN_MID_BACK_UNROUNDED_VOWEL], include: false },
            { name: [OPEN_MID_CENTRAL_ROUNDED_VOWEL], include: false },
            { name: [OPEN_MID_CENTRAL_UNROUNDED_VOWEL], include: false },
            { name: [OPEN_MID_FRONT_ROUNDED_VOWEL], include: false },
            { name: [OPEN_MID_FRONT_UNROUNDED_VOWEL], include: false }
        ]
    },
}

let names = {
    V_ALVEOLAR_APPROXIMANT,
    V_ALVEOLAR_FRICATIVE,
    V_ALVEOLAR_LATERAL_APPROXIMANT,
    V_ALVEOLAR_LATERAL_FRICATIVE,
    V_ALVEOLAR_NASAL,
    V_ALVEOLAR_PLOSIVE,
    V_ALVEOLAR_TAP,
    V_ALVEOLAR_TRILL,
    V_BILABIAL_FRICATIVE,
    V_BILABIAL_NASAL,
    V_BILABIAL_PLOSIVE,
    V_BILABIAL_TRILL,
    V_DENTAL_FRICATIVE,
    V_DENTAL_LATERAL_APPROXIMANT,
    V_DENTAL_NASAL,
    V_GLOTTAL_FRICATIVE,
    V_LABIODENTAL_APPROXIMANT,
    V_LABIODENTAL_FLAP,
    V_LABIODENTAL_FRICATIVE,
    V_LABIODENTAL_NASAL,
    V_DENTAL_PLOSIVE,
    V_PALATAL_APPROXIMANT,
    V_PALATAL_FRICATIVE,
    V_PALATAL_LATERAL_APPROXIMANT,
    V_PALATAL_NASAL,
    V_PALATAL_PLOSIVE,
    V_PHARYNGEAL_FRICATIVE,
    V_POSTALVEOLAR_FRICATIVE,
    V_RETROFLEX_APPROXIMANT,
    V_RETROFLEX_FLAP,
    V_RETROFLEX_FRICATIVE,
    V_RETROFLEX_LATERAL_APPROXIMANT,
    V_RETROFLEX_NASAL,
    V_RETROFLEX_PLOSIVE,
    V_UVULAR_FRICATIVE,
    V_UVULAR_NASAL,
    V_UVULAR_PLOSIVE,
    V_UVULAR_TRILL,
    V_VELAR_APPROXIMANT,
    V_VELAR_FRICATIVE,
    V_VELAR_LATERAL_APPROXIMANT,
    V_VELAR_NASAL,
    V_VELAR_PLOSIVE,
    VL_ALVEOLAR_FRICATIVE,
    VL_ALVEOLAR_LATERAL_FRICATIVE,
    VL_ALVEOLAR_PLOSIVE,
    VL_BILABIAL_FRICATIVE,
    VL_BILABIAL_PLOSIVE,
    VL_DENTAL_FRICATIVE,
    VL_GLOTTAL_FRICATIVE,
    VL_GLOTTAL_PLOSIVE,
    VL_LABIODENTAL_FRICATIVE,
    VL_DENTAL_PLOSIVE,
    VL_PALATAL_FRICATIVE,
    VL_PALATAL_PLOSIVE,
    VL_PHARYNGEAL_FRICATIVE,
    VL_POSTALVEOLAR_FRICATIVE,
    VL_RETROFLEX_FRICATIVE,
    VL_RETROFLEX_PLOSIVE,
    VL_UVULAR_FRICATIVE,
    VL_UVULAR_PLOSIVE,
    VL_VELAR_FRICATIVE,
    VL_VELAR_PLOSIVE,
    CLOSE_BACK_ROUNDED_VOWEL,
    CLOSE_BACK_UNROUNDED_VOWEL,
    CLOSE_CENTRAL_ROUNDED_VOWEL,
    CLOSE_CENTRAL_UNROUNDED_VOWEL,
    CLOSE_FRONT_ROUNDED_VOWEL,
    CLOSE_FRONT_UNROUNDED_VOWEL,
    CLOSE_MID_BACK_ROUNDED_VOWEL,
    CLOSE_MID_BACK_UNROUNDED_VOWEL,
    CLOSE_MID_CENTRAL_ROUNDED_VOWEL,
    CLOSE_MID_CENTRAL_UNROUNDED_VOWEL,
    CLOSE_MID_FRONT_ROUNDED_VOWEL,
    CLOSE_MID_FRONT_UNROUNDED_VOWEL,
    MID_CENTRAL_VOWEL,
    NEAR_CLOSE_NEAR_BACK_ROUNDED_VOWEL,
    NEAR_CLOSE_NEAR_FRONT_ROUNDED_VOWEL,
    NEAR_CLOSE_NEAR_FRONT_UNROUNDED_VOWEL,
    NEAR_OPEN_CENTRAL_UNROUNDED_VOWEL,
    NEAR_OPEN_FRONT_UNROUNDED_VOWEL,
    OPEN_BACK_ROUNDED_VOWEL,
    OPEN_BACK_UNROUNDED_VOWEL,
    OPEN_CENTRAL_UNROUNDED_VOWEL,
    OPEN_FRONT_ROUNDED_VOWEL,
    OPEN_FRONT_UNROUNDED_VOWEL,
    OPEN_MID_BACK_ROUNDED_VOWEL,
    OPEN_MID_BACK_UNROUNDED_VOWEL,
    OPEN_MID_CENTRAL_ROUNDED_VOWEL,
    OPEN_MID_CENTRAL_UNROUNDED_VOWEL,
    OPEN_MID_FRONT_ROUNDED_VOWEL,
    OPEN_MID_FRONT_UNROUNDED_VOWEL,
}

export { symbols, specs, names };